<?php
$gejala = array(
    "Tampilan tidak muncul pada monitor saat PC dinyalakan",
    "Keluar garis-garis vertical di layar monitor",
    "Tampak blok hitam atau gambar terlihat tidak simetris dilayar monitor",
    "Tampilan monitor buram",
    "Monitor seperti berkedip-kedip saat digunakan",
    "Size gambar tidak jelas",
    "Tampilan tampak bergelombang",
    "Tombol keyboard tidak berfungsi sama sekali",
    "Keyboard tidak terdeteksi",
    "Tombol keyboard tertukar huruf",
    "Terdengar bunyi beep",
    "PC restart terus menerus",
    "Pointer mouse tidak bergerak",
    "Pointer mouse tidak berjalan normal",
    "Double klik",
    "Tidak bereaksi apa-apa saat PC dinyalakan",
    "Tidak ada lampu indicator (LED) yang menyala",
    "Kipas power supply tidak berputar",
    "Lampu indicator monitor bekedip-kedip.",
    "Tidak ada suara beep dimonitor",
    "Kipas power supply dan kipas prossesor berputar",
    "Loading data atau sistem lambat",
    "Terdengar bunyi tidak normal",
    "File tiba-tiba hilang",
    "Tidak bisa membaca CD/DVD",
    "Layar terlihat putih",
    "VGA atau animasi tidak berjalan dengan baik",
    "Tampilan gambar pecah-pecah",
    "Putaran dynamo CD/DVD kencang tapi tidak terbaca",
    "Tidak bisa digunakan untuk burning",
    "CD/DVD ROM tidak bisa terbuka sama sekali",
    "Kinerja komputer semakin menurun",
    "File rusak secara acakan",
    "Layar tampilan berkedip dengan layar biru",
    "Tidak bisa mengeluarkan suara melalui speaker",
    "Suara yang dihasilkan tidak jelas",
    "Sistem operasi tidak mengeluarkan suara windows",
    "Local Area Connection tidak muncul",
    "Proses transmisi data yang lambat",
    "Sering mengalami kegagalan server"
);

$masalah = array("Kerusakan Monitor",
"Kerusakan Keyboard",
"Kerusakan Mouse",
"Kerusakan Power Supply",
"Kerusakan Motherboard",
"Kerusakan Harddisk",
"Kerusakan VGA Card",
"Kerusakan CD/DVD Rom",
"Kerusakan RAM",
"Kerusakan Sound Card",
"Kerusakan LAN Card");
